### ISSUE TITLE
`intent_pres_party` nulls

### ISSUE THREAD

**Issue by vcbradley** [kuriwaki/cces_cumulative#45]
`intent_pres_party` is null for Libertarian and Green party preference

![Screen Shot 2021-02-05 at 12 48 38 PM](https://user-images.githubusercontent.com/8030952/107069839-7df44e80-67b0-11eb-9ee4-5b2f5253de19.png)

**Comment by kuriwaki** [comment]
I think this was somewhat intentional, but you're right that at the _least_ it should be be `intent_pres_party == "Other Candidate".` for Green/Lbt voters. I will keep this thread posted on the status of fixing this, but in the meantime I would work with  `intent_pres_16` (e.g. with `dplyr::recode`).

**Comment by kuriwaki** [comment]
This is fixed in the code with the following output. 

I will close this issue when an updated version is actually on dataverse. In the meantime, if the fixed dataset would be useful, please email me and I can send.

Thanks for catching this!

```
> as.data.table(cces_all)[year == 2016, .N, .(year, intent_pres_party, intent_pres_16)]
   year intent_pres_party                intent_pres_16     N
1: 2016        Republican     Donald Trump (Republican) 19227
2: 2016        Democratic    Hillary Clinton (Democrat) 27502
3: 2016              <NA>                  I'm Not Sure  6536
4: 2016              <NA> I Won't Vote in this Election  3312
5: 2016       Third Party            Jill Stein (Green)  1400
6: 2016       Third Party    Gary Johnson (Libertarian)  3145
7: 2016              <NA>                          <NA>  1598
8: 2016   Other Candidate                         Other  1880

# Third party options were not named in the `voted` variables

> as.data.table(cces_all)[year == 2016, .N, .(year, voted_pres_party, voted_pres_16)]
   year voted_pres_party           voted_pres_16     N
1: 2016       Republican            Donald Trump 18755
2: 2016             <NA>                    <NA> 19358
3: 2016       Democratic          Hilary Clinton 22136
4: 2016  Other Candidate    Other / Someone Else  4041
5: 2016             <NA> Not Sure / Don't Recall   229
6: 2016     Did not Vote            Did Not Vote    81
```

**Comment by kuriwaki** [comment]
Dataset posted: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/II2DB6
