### ISSUE TITLE
spreadsheet with summary vars of each geography

### ISSUE THREAD

**Issue by kuriwaki** [kuriwaki/cces_cumulative#9]
A place you might get started is: http://nrs.harvard.edu/urn-3:hul.eresource:socialex

**Comment by sdimauro** [comment]
@kuriwaki Social explorer seems to be all maps.  How were you able to extract data for only congressional districts like you did the other day?

**Comment by kuriwaki** [comment]
Try the Table tab to your top-right. https://www.socialexplorer.com/explore/tables

**Comment by kuriwaki** [comment]
@sdimauro 
and when we have the table, let's download by `TAB` or `csv` format, which seems like will get everything in one file (see attached). If TAB, let's also download the `.dct` and `.do` files associated with it. That might help us label the columns into meaningful labels. 

<img width="662" alt="screenshot 2017-06-29 23 08 59" src="https://user-images.githubusercontent.com/8290417/27692260-331fd5a2-5d21-11e7-8de4-6d4f3658fe7a.png">

**Comment by sdimauro** [comment]
Ok sounds good!  What kind of demographic data should I select?  Here's a screenshot of what I am looking at.
![screen shot 2017-06-29 at 10 45 26 am](https://user-images.githubusercontent.com/29707933/27693702-2ad262f2-5cb8-11e7-917d-3279ec27499a.png)

**Comment by kuriwaki** [comment]
if it lets you, we can "Select All" and download everything; that way we can handpick the variables later.

In addition to CDs, we might look at States for the geographic boundaries.

And other than the 2010 Census, the American Community Survey (5-year) from 2006-2016 will be another source we want to download from. They ask about citizenship status.

**Comment by sdimauro** [comment]
Ok sounds good, thanks.  I'll get on it!

**Comment by kuriwaki** [comment]
beyond scope of this project; revisit later.
